// Generates the static SEO/legal files that live in /public:
//   favicon.svg, site.webmanifest, robots.txt, sitemap.xml, privacy/terms/cookies pages,
//   node scripts/build-static.cjs      (run scripts/industries/build.cjs first)
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SITE = process.env.SITE_URL || 'https://innovsol.ai';
const UPDATED = '30 September 2026';
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8').replace(/^﻿/, '');
const write = (p, s) => { fs.mkdirSync(path.dirname(path.join(ROOT, p)), { recursive: true }); fs.writeFileSync(path.join(ROOT, p), s); };
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/* ---------- icons / manifest / robots ---------- */
write('public/favicon.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#3f6cb5"/><g fill="none" stroke="#fff" stroke-width="4.5" stroke-linecap="round"><circle cx="20" cy="18" r="4.5"/><circle cx="32" cy="14" r="4.5" fill="#faa720" stroke="#faa720"/><circle cx="44" cy="18" r="4.5"/><path d="M20 23v24M32 19v28M44 23v24"/></g></svg>`);
write('public/site.webmanifest', JSON.stringify({ name: 'Innovsol', short_name: 'Innovsol', description: 'Enterprise AI engineering and digital transformation', start_url: '/', display: 'browser', background_color: '#ffffff', theme_color: '#3f6cb5', icons: [{ src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' }, { src: '/favicon-192.png', sizes: '192x192', type: 'image/png' }, { src: '/favicon-512.png', sizes: '512x512', type: 'image/png' }] }, null, 2));
write('public/robots.txt', `User-agent: *\nAllow: /\nDisallow: /api/\n\nSitemap: ${SITE}/sitemap.xml\n`);

/* ---------- site extras bundle: config + consent + monitoring + booking ---------- */
const siteCfg = JSON.parse(read('content/site.json'));
const env = process.env;
const pub = {
  siteName: siteCfg.siteName, url: SITE, email: siteCfg.email, phone: siteCfg.phone, address: siteCfg.address,
  legalName: siteCfg.legalName, registration: siteCfg.registration,
  bookingUrl: env.BOOKING_URL || siteCfg.bookingUrl,
  analytics: { ga4Id: env.GA4_ID || siteCfg.analytics.ga4Id, plausibleDomain: env.PLAUSIBLE_DOMAIN || siteCfg.analytics.plausibleDomain },
  turnstileSiteKey: env.TURNSTILE_SITE_KEY || siteCfg.turnstileSiteKey,
};
write('public/shell/site-extras.js', '/* generated by scripts/build-static.cjs from content/site.json — do not edit */\nwindow.__SITE__ = ' + JSON.stringify(pub) + ';\n' + ['consent', 'monitor', 'site'].map((n) => read('scripts/site/' + n + '.js')).join('\n'));

/* ---------- legal pages (shared site shell) ---------- */
const shellNav = read('src/modules/layout/navbar/navbar.html').replaceAll('href="#', 'href="/#').replace('<nav id="nav">', '<nav id="nav" class="sc" aria-label="Main">');
const shellFooter = read('src/modules/layout/footer/footer.html').replaceAll('href="#', 'href="/#');

const LEGAL = {
  privacy: {
    title: 'Privacy Policy',
    desc: 'How Innovsol collects, uses and protects personal information submitted through this website.',
    body: `
<p>Innovsol ("we", "us") respects your privacy. This policy explains what personal information we collect through this website, why, and the choices you have.</p>
<h2>Information we collect</h2>
<ul><li><strong>Contact form:</strong> name, work email, phone (optional), company, industry, enquiry type and your message.</li>
<li><strong>Email links:</strong> when you use "Apply Now" or "Download Playbook", your own email app sends us the details you choose to include, including any resume you attach.</li>
<li><strong>Technical data:</strong> basic server logs (IP address, browser, pages requested) used for security and reliability.</li></ul>
<h2>How we use it</h2>
<p>To respond to your enquiry, evaluate job applications, send requested materials, and keep the site secure. We do not sell personal information.</p>
<h2>Sharing</h2>
<p>We share information only with service providers that help us run the site (for example email delivery and hosting) and where required by law. This site loads fonts from Google Fonts and some images from Unsplash, which may receive your IP address.</p>
<h2>Retention</h2>
<p>Enquiries are kept for as long as needed to respond and for reasonable business records. Job applications are kept for up to 12 months unless you ask us to delete them sooner.</p>
<h2>Your rights</h2>
<p>You can request access, correction or deletion of your personal information by emailing <a href="mailto:hello@innovsol.ai">hello@innovsol.ai</a>.</p>
<h2>Candidate portal and job applications</h2>
<p>If you create a portal account or apply for a role we process your name, email, password (stored hashed by our authentication provider), cover note, resume and application status. Resumes are kept in private storage visible only to you and Innovsol hiring staff. Applications are kept for up to 12 months after the role closes unless you ask us to delete them sooner. You can delete your account and all associated data yourself from the portal.</p>
<h2>Service providers (processors)</h2>
<p>We use: a hosting provider for this website; Supabase for the candidate portal database, authentication and file storage; an email delivery provider for messages we send; and, only if you opt in, an analytics provider. They process data on our instructions.</p>
<h2>Consent and legal basis</h2>
<p>We process enquiry and application data to respond to your request and, for applications, to take steps at your request before a possible employment relationship. Optional analytics run only with your consent, which you can withdraw at any time from "Cookie settings" in the footer. Where India's Digital Personal Data Protection Act, 2023 or the EU/UK GDPR applies, you have the rights described below.</p>
<h2>International transfers</h2>
<p>Our providers may process data in countries other than your own. Where required, we rely on appropriate safeguards such as contractual clauses.</p>
<h2>Children</h2>
<p>This website is not directed at children and we do not knowingly collect their personal data.</p>
<h2>Security</h2>
<p>We use encryption in transit, input validation, row-level access controls and optional multi-factor authentication to protect information. No method of transmission is completely secure.</p>
<h2>Contact</h2>
<p>Questions about this policy: <a href="mailto:hello@innovsol.ai">hello@innovsol.ai</a>.</p>`,
  },
  cookies: {
    title: 'Cookie Policy',
    desc: 'How Innovsol uses cookies and browser storage on this website.',
    body: `
<p>This website is designed to work without tracking cookies.</p>
<h2>What we store</h2>
<ul><li><strong>Strictly necessary:</strong> none required to browse the site.</li>
<li><strong>Preferences:</strong> if you click "Save Job" on a job page, your choice is stored in your browser's local storage on your own device. It is never sent to us.</li>
<li><strong>Consent choice:</strong> if analytics is enabled on the site, your accept / decline choice is stored in your browser's local storage so we do not ask again on every page.</li>
<li><strong>Analytics (optional):</strong> only when enabled by us <em>and</em> accepted by you. It may set cookies to count visits and see which pages are useful. No advertising or cross-site tracking cookies are used. Change your mind any time via "Cookie settings" in the footer.</li></ul>
<h2>Third-party content</h2>
<p>Fonts (Google Fonts) and some images (Unsplash) are loaded from those providers and may set their own technical data. See their policies for details.</p>
<h2>Managing storage</h2>
<p>You can clear local storage and cookies at any time from your browser settings.</p>
<p>Questions: <a href="mailto:hello@innovsol.ai">hello@innovsol.ai</a>.</p>`,
  },
  terms: {
    title: 'Terms of Use',
    desc: 'Terms governing your use of the Innovsol website, including acceptable use, intellectual property and job applications.',
    body: `
<p>By using this website you agree to these terms.</p>
<h2>Use of the site</h2>
<p>You may use the site for lawful purposes only. Do not attempt to disrupt it, probe it for vulnerabilities without permission, or submit unlawful, misleading or harmful content through our forms.</p>
<h2>Intellectual property</h2>
<p>Site content, design and branding belong to Innovsol or its licensors. You may not copy or redistribute them without written permission, except for personal, non-commercial reference.</p>
<h2>Information on the site</h2>
<p>Content is provided for general information. Figures and outcomes shown on industry pages are indicative and vary by engagement. They are not a guarantee of results.</p>
<h2>Job applications</h2>
<p>Submitting an application does not create an employment relationship. We may contact you using the details you provide.</p>
<h2>Liability</h2>
<p>To the extent permitted by law, the site is provided "as is" and we are not liable for indirect or consequential loss arising from its use.</p>
<h2>Changes</h2>
<p>We may update these terms; the version on this page applies from the date shown above. Contact: <a href="mailto:hello@innovsol.ai">hello@innovsol.ai</a>.</p>`,
  },
};

const legalCss = `.legal{max-width:780px;margin:0 auto;padding:calc(104px + 40px) 20px 72px;color:#1f2430}
.legal h1{font-size:clamp(1.8rem,4vw,2.6rem);color:#0b1022;margin-bottom:6px}
.legal .upd{color:#5a6a7a;font-size:.9rem;margin-bottom:28px}
.legal h2{font-size:1.15rem;margin:28px 0 8px;color:#0b1022}
.legal p,.legal li{line-height:1.7;margin-bottom:10px}
.legal ul{padding-left:1.2rem}
.legal a{color:#3f6cb5;text-decoration:underline}`;

for (const [slug, l] of Object.entries(LEGAL)) {
  const url = `${SITE}/${slug}.html`;
  write(`public/${slug}.html`, `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(l.title)} | Innovsol</title>
<meta name="description" content="${esc(l.desc)}">
<link rel="canonical" href="${url}">
<meta name="robots" content="index, follow">
<meta property="og:title" content="${esc(l.title)} | Innovsol"><meta property="og:description" content="${esc(l.desc)}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><meta property="og:image" content="${SITE}/og-image.jpg">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/shell/site-shell.css">
<style>${legalCss}</style>
</head>
<body>
${shellNav}
<main class="legal" id="main"><h1>${esc(l.title)}</h1><p class="upd">Last updated: ${UPDATED}</p>${l.body}</main>
${shellFooter}
<script src="/shell/navbar.js" defer></script>
<script src="/shell/site-extras.js" defer></script>
<script>addEventListener('scroll',function(){document.getElementById('nav').classList.add('sc')},{passive:true})</script>
</body>
</html>
`);
}

/* ---------- job pages (built by scripts/jobs/build.cjs; only listed here for the sitemap) ---------- */
const jobs = fs.readdirSync(path.join(ROOT, 'public/careers')).filter((x) => x.endsWith('.html')).map((f) => `/careers/${f}`);

/* ---------- sitemap ---------- */
const today = new Date().toISOString().slice(0, 10);
const inds = fs.readdirSync(path.join(ROOT, 'public/industries')).filter((x) => x.endsWith('.html')).map((x) => `/industries/${x}`);
const urls = [['/', 1.0, 'weekly'], ['/careers', 0.8, 'weekly'], ...inds.map((u) => [u, 0.9, 'monthly']), ...jobs.map((u) => [u, 0.6, 'weekly']), ...((fs.existsSync(path.join(ROOT, 'scripts/.pages-manifest.json')) ? JSON.parse(read('scripts/.pages-manifest.json')) : []).map((m) => [m.path, m.priority, m.freq])), ['/privacy.html', 0.2, 'yearly'], ['/cookies.html', 0.2, 'yearly'], ['/terms.html', 0.2, 'yearly']];
write('public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(([u, pr, fr]) => `  <url><loc>${SITE}${u}</loc><lastmod>${today}</lastmod><changefreq>${fr}</changefreq><priority>${pr}</priority></url>`).join('\n')}\n</urlset>\n`);
console.log(`static files written: ${urls.length} sitemap urls, ${Object.keys(LEGAL).length} legal pages`);
