// Turns content/jobs.json into supabase/seed.sql so the portal starts with the same roles as the website.
//   node scripts/supabase-seed.cjs
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const jobs = JSON.parse(fs.readFileSync(path.join(root, 'content/jobs.json'), 'utf8'));
const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const rows = Object.values(jobs).map((j) => `  (${q(j.slug)}, ${q(j.title)}, ${q(j.about)}, ${q((j.meta[0] || {}).text || 'Remote')}, ${q((j.meta[1] || {}).text || 'Full-Time')}, true)`);
fs.writeFileSync(path.join(root, 'supabase/seed.sql'),
`-- Generated by scripts/supabase-seed.cjs from content/jobs.json. Safe to re-run.
insert into public.jobs (slug, title, summary, location, employment, published) values
${rows.join(',\n')}
on conflict (slug) do update set title = excluded.title, summary = excluded.summary, location = excluded.location, employment = excluded.employment;
`);
console.log('supabase/seed.sql written for', rows.length, 'jobs');
